spring.application.name=DBDemo
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=



book.bookName="Art of being positive"
book.author=azzam

management.endpoints.web.exposure.include=health,info,beans,env

server.port=8081
