spring.application.name=Assignment3
spring.datasource.url=jdbc:mysql://localhost:3306/jpa_playground
spring.datasource.username=root
spring.datasource.password=Azzam@123

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.hibernate.SQL=DEBUG
server.port=9090