import java.util.Random;
import java.util.concurrent.*;

public class D9J4 {
    public static void main(String[] args) {
        Callable<Integer> randomTask = () -> {
            Random random = new Random();
            int value = random.nextInt(100);
            System.out.println("Generated by thread: " + Thread.currentThread().getName());
            return value;
        };

        ExecutorService executor = Executors.newSingleThreadExecutor();

        Future<Integer> future = executor.submit(randomTask);

        try {
            Integer result = future.get();
            System.out.println("Random number returned by thread: " + result);
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        } finally {
            executor.shutdown();
        }
    }
}
